[build]
command = "make build && npm run build"
publish = "out"

# [[redirects]]
# from = "/webhooks/twilio"
# to = "/.netlify/functions/webhooks_twilio_js"
# status = 200

# [[redirects]]
# from = "/generate/image"
# to = "/.netlify/functions/generate_image_js"
# status = 200

[[redirects]]
from = "/webhooks/twilio"
to = "/.netlify/functions/webhooks_twilio_rs"
status = 200

[[redirects]]
from = "/generate/image"
to = "/.netlify/functions/generate_image_rs"
status = 200

[functions]
included_files = ["netlify/functions/shout-out-image/image.js"]

[template.environment]
DATABASE_URL = "Database Connection String"
