[build]
command = "make build & npm run deploy"
publish = "out"

[[redirects]]
from = "/webhooks/twilio"
to = "/.netlify/functions/webhooks_twilio_js"
status = 200

[[redirects]]
from = "/webhooks/twilio_rs"
to = "/.netlify/functions/webhooks_twilio_rs"
status = 200

[functions]
node_bundler = "esbuild"
# external_node_modules = ["pg"]
# included_files = ["netlify/certs/*"]
